### PR TITLE
fix example parsing

### PR DESCRIPTION
**Pull request by KerstenBreuer**
so sorry @deepakunni3. I messed with your script. Now it should work.

### CODE REVIEW

**Comment by deepakunni3** [comment]
Hah, I was just debugging that script :D 

Good catch! Thanks for the PR

**Review by deepakunni3 — APPROVED** [review]

**Comment by KerstenBreuer** [comment]
Sorry, I was sure I tested it before committing and it worked. But I must have messed it up after that.

**Comment by deepakunni3** [comment]
No worries. I took the liberty of committing a few changes to this branch. Mainly with the devcontainer config and dependencies.

**Comment by KerstenBreuer** [comment]
Sure looks good. But do we really need "requests==2.26.0" in the actual service? If we just need it in the population script, then I guess it's fine to just have it in the `dev` extras (see line 63 in setup.cfg). If you run `.devcontainer/dev_install` all of the extras should be installed.

**Comment by deepakunni3** [comment]
Good point @KerstenBreuer ! I see the requests is already in the dev section. 

Removed the requests from the core dependencies.

**Comment by KerstenBreuer** [comment]
Looks perfect now @deepakunni3. Thanks also for the other changes.

**Pull request merged**
