### PR TITLE
Update loading script (GDEV-147)

### PR DESCRIPTION
**Pull request by deepakunni3**
This PR adds the following:
- Add script to populate metadata store via the API
- Add script to delete all metadata records from a given MongoDB store
- Add Typer CLI to `generate_openapi_yaml.py` script

@KerstenBreuer FYI

### CODE REVIEW

**Comment by KerstenBreuer** [comment]
Great thanks a lot, Deepak. I added a ticket for this to Jira, so that this shows up as your sprint achievement ;)

**Review by KerstenBreuer — CHANGES_REQUESTED** [review]
Looks really great. Thanks a lot.

I just have a couple of suggestion which I put in PR #13 (that is trying to merge into this branch). 

Could you have a look at them.

Funny, you had the same idea as me of creating a script to get the openapi.yaml out of FastAPI. Maybe you could also have a look at it.  It's already in the template repository:
https://github.com/ghga-de/microservice-repository-template/blob/dev/.devcontainer/openapi_from_app.py

**Comment by deepakunni3** [comment]
@KerstenBreuer D'oh! I should have checked the template repo before writing a script to make the openapi.yaml 😅 

Thanks for improving on the scripts! They look so much more neat 👍

**Comment by KerstenBreuer** [comment]
No worries, thanks a lot Deepak

**Review by KerstenBreuer — APPROVED** [review]

**Pull request merged**
