### PR TITLE
feature/cd_flow (GDEV-39)

### PR DESCRIPTION
**Pull request by walzph**
same as https://github.com/ghga-de/sandbox-storage/pull/15

### CODE REVIEW

**Comment by deepakunni3** [comment]
@walzph Is this ready to be merged?

**Comment by walzph** [comment]
I think it can be merged. Although the docker hub secrets might not be configured for this repo yet or are they @KerstenBreuer?

But go ahead, this won't break anything 🙂

**Comment by KerstenBreuer** [comment]
No, not yet, will take care of that tomorrow.

**Comment by deepakunni3** [comment]
Thanks @KerstenBreuer

**Pull request merged**
